version: '3.8'

services:
  web-dev:
    build:
      context: .
      dockerfile: docker/Dockerfile
      target: development
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
    ports:
      - "5173:5173"
    command: npm run dev
